### ISSUE TITLE
So where is the required requirements? 

### ISSUE THREAD

**Issue by Huzzla101** [i64-sudo/Neo-Clipper#2]
I wanteed to test out ur file and i can open it and run it as in ur picture but in end i get this msg:

    [>] Obfuscate/Encrypt Executable? (May Break When Using External Files) [Y/N] y
sh: 1: python: not found
Traceback (most recent call last):
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 119, in <module>
    neo.__init__()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 116, in __init__
    neo.qv()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 112, in qv
    neo.compile()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 79, in compile
    encode_obfuscate()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 69, in encode_obfuscate
    with open(f'{vPath}\\Obfuscated_src.py', 'r') as pf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Neo-Clipper-main\\Obfuscated_src.py'

And this is without installing any requirementws but i see in one of ur folders u have a file called tool_obfuscation.py  i dont know if that should change name to the file not found ? so i tried but same error.. Also i have python installed off course. `Please revert Sir

**Comment by Huzzla101** [comment]
now i tried with no to encrypt Exe and this error comes up BUT the file it looking for is there.... see error:


 [>] Obfuscate/Encrypt Executable? (May Break When Using External Files) [Y/N] n
Traceback (most recent call last):
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 119, in <module>
    neo.__init__()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 116, in __init__
    neo.qv()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 112, in qv
    neo.compile()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 81, in compile
    original_build()
  File "/mnt/c/Neo-Clipper-main/neo-clip.py", line 59, in original_build
    with open(f'{vPath}\\lib\\src.py', 'r', encoding='utf-8') as pf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Neo-Clipper-main\\lib\\src.py'     <----i have the dir /lib and src.py from your zip.... So the zip file have all needed requirements , thats why u removed the requirements.txt file? if not then where is the txt file ??

**Comment by Huzzla101** [comment]
ok so now i started it from windows CMD , u dont need to type when inside the dir , python (filename) just enter the filename and it will start in  CMD , but from linuc etc u have to type also python or python3 or even pip3 .. i accept all =) but so now windows part tell me they dont know but if all ok then 

src.exe should be in a map that not even is there....? see picture and please give me the final requirements so i can use ur respected tool
![whats this lol ](https://github.com/user-attachments/assets/ad57f2ca-bc48-49e5-80eb-2d2bba050c3a)
But i have in my dir /lib a file i created today called src.py is that the file then ? so it worked even tho with error or is this file halfway or half made so it wont work... hmm
